import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const styles = await readFile(new URL('../public/styles.css', import.meta.url), 'utf8');
const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
const i18n = await readFile(new URL('../public/i18n.js', import.meta.url), 'utf8');

test('task pane has bounded desktop and touch scrolling styles', () => {
  assert.match(styles, /\.app-shell \{[^}]*height: 100dvh;[^}]*overflow: hidden;/);
  assert.match(html, /<meta name="viewport" content="[^"]*maximum-scale=1, user-scalable=no[^"]*" \/>/);
  assert.match(html, /<meta name="mobile-web-app-capable" content="yes" \/>/);
  assert.match(styles, /html \{[^}]*touch-action: pan-x pan-y;/);
  assert.match(styles, /\.task-pane \{[^}]*overflow-y: auto;[^}]*overscroll-behavior-y: contain;[^}]*-webkit-overflow-scrolling: touch;/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.task-pane \{[^}]*height: 100%;[^}]*overflow-y: auto;[^}]*touch-action: pan-y;/);
  assert.match(styles, /\.task-detail \{[^}]*overflow: hidden;[^}]*overscroll-behavior: none;/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.detail-scroll \{[^}]*overflow-y: auto;[^}]*overscroll-behavior: contain;[^}]*touch-action: pan-y;/);
  assert.match(styles, /\.composer-dock \{[^}]*overscroll-behavior: none;/);
  assert.match(styles, /\.account-badge span \{[^}]*text-overflow: ellipsis;[^}]*white-space: nowrap;/);
  assert.match(styles, /\.version-support-actions \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(styles, /\.version-action \{[^}]*display: flex;[^}]*align-items: center;[^}]*justify-content: center;/);
  assert.match(styles, /\.version-dashboard \{[^}]*grid-auto-rows: max-content;[^}]*align-content: start;/);
  assert.match(styles, /\.success-share-card \{[^}]*min-height: 66px;[^}]*grid-template-columns: 36px minmax\(0, 1fr\) auto;/);
  assert.match(styles, /@media \(max-width: 360px\)[\s\S]*\.success-share-card \{[^}]*grid-template-columns: minmax\(0, 1fr\) auto;/);
  assert.match(styles, /@media \(max-width: 360px\)[\s\S]*\.success-share-mark \{[^}]*display: none;/);
  assert.doesNotMatch(html, /id="success-card"/);
  assert.match(html, /<div class="brand-title-row">[\s\S]*<h1[^>]*>[^<]+<\/h1>[\s\S]*<button id="version-button"/);
  assert.doesNotMatch(html, /<p>[\s\S]*?<button id="version-button"[\s\S]*?<\/p>/);
  assert.match(styles, /\.brand-title-row \{[^}]*display: flex;[^}]*align-items: center;/);
  assert.match(styles, /\.brand h1 \{[^}]*overflow: hidden;[^}]*text-overflow: ellipsis;[^}]*white-space: nowrap;/);
  assert.match(styles, /\.version-button \{[^}]*flex: 0 0 auto;[^}]*overflow: hidden;/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.account-badge \{[^}]*max-width: 92px;/);
  assert.match(styles, /--top-control-size: 40px;/);
  assert.match(styles, /\.brand-mark \{[^}]*width: var\(--top-control-size\);[^}]*height: var\(--top-control-size\);[^}]*flex: 0 0 var\(--top-control-size\);/);
  assert.match(styles, /\.language-button \{[^}]*width: var\(--top-control-size\);[^}]*height: var\(--top-control-size\);[^}]*border-radius: 13px;/);
  assert.match(styles, /\.icon-button \{[^}]*width: var\(--top-control-size\);[^}]*height: var\(--top-control-size\);[^}]*border-radius: 13px;/);
  assert.match(styles, /\.icon-button\.is-refreshing svg \{[^}]*animation: refresh-spin \.7s linear infinite;/);
  assert.doesNotMatch(html, /class="summary-row"/);
  assert.doesNotMatch(i18n, /summary\.(?:running|queued|all)/);
  assert.match(styles, /\.filter-count \{[^}]*min-width: 16px;[^}]*display: inline-grid;/);
  assert.match(styles, /\.task-toolbar \{[^}]*overflow: hidden;[^}]*border: 1px solid/);
  assert.match(styles, /\.filters \{[^}]*min-width: 0;[^}]*overflow-x: auto;[^}]*overscroll-behavior-x: contain;/);
  assert.match(styles, /\.filter \{[^}]*flex: 0 0 auto;/);
  assert.doesNotMatch(styles, /new-task-button|new-task-form|project-picker|queue-steer/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.filter-count \{[^}]*min-width: 14px;[^}]*height: 14px;/);
  assert.match(styles, /\.usage-stats \{[^}]*grid-auto-flow: column;[^}]*grid-auto-columns: minmax\(0,1fr\);/);
  assert.match(styles, /\.usage-stat \{[^}]*flex-direction: column;[^}]*border-left:/);
  assert.match(styles, /\.task-card\.is-unread:not\(\.is-selected\) \{[^}]*border-color:/);
  assert.match(styles, /\.unread-dot \{[^}]*width: 7px;[^}]*background: var\(--blue\);/);
  assert.match(styles, /\.task-card-head \{[^}]*grid-template-columns: minmax\(0, 1fr\) max-content;/);
  assert.match(styles, /\.task-card-head h3 \{[^}]*overflow: hidden;[^}]*text-overflow: ellipsis;[^}]*white-space: nowrap;/);
  assert.match(styles, /\.task-card-meta \{[^}]*white-space: nowrap;/);
  assert.match(styles, /\.modal-sheet\.activity-sheet \{[^}]*height: min\(92dvh, 880px\);[^}]*background: #0b1019;/);
  assert.match(styles, /\.activity-metrics \{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\);/);
  assert.match(styles, /\.activity-chart-line \{[^}]*stroke: var\(--activity-accent\);[^}]*stroke-linecap: round;/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.modal-sheet\.activity-sheet \{[^}]*height: 100dvh;[^}]*border-radius: 0;/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*\.activity-metrics \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
});
